/* ================= nutricionista: menu e telas principais ================= */
const NAV=[['dash','Dashboard'],['patients','Pacientes'],['consults','Consultas'],['agenda','Agenda'],['evals','Avaliações'],['diets','Dietas'],['club','BentoNutriClub'],['msgs','Mensagens'],['reports','Relatórios'],['settings','Configurações']];
function drawNav(){$('#nav').innerHTML=NAV.map(([k,t])=>`<a href="#" data-a="nav" data-k="${k}" class="${(S.nav===k)?'on':''}" ${S.nav===k?'aria-current="page"':''}>${t}</a>`).join('')}
function render(html,after,load=true){const m=$('#main');if(!load){m.innerHTML=html;after&&after();return}m.innerHTML=skel();clearTimeout(render.t);render.t=setTimeout(()=>{m.innerHTML=html;after&&after()},180)}
function go(k){S.nav=k;S.pid=null;drawNav();VIEWS[k]()}
const statusPill=s=>`<span class="pill ${ST[s][1]}">${ST[s][0]}</span>`;
const VIEWS={
 dash(){const AL=[['critical','Joana Alves está sem registros há mais de 4 dias.'],['warning','Joana Alves: adesão semanal abaixo de 50%.'],['warning','Camila Reis está sem registros há mais de 48 h.'],['info','Adesão de Pedro Nunes caiu 25 pontos.']];
  render(`<div class="kpis"><div class="card"><small>Pacientes ativos</small><b>42</b></div><div class="card"><small>Adesão média</small><b>81%</b></div><div class="card"><small>Check-ins hoje</small><b>17</b></div><div class="card"><small>Sem registro &gt;48h</small><b style="color:var(--warn)">5</b></div><div class="card"><small>Consultas hoje</small><b>4</b></div></div>
  <div class="card tbl"><table><thead><tr><th>Paciente</th><th>Último check-in</th><th>Adesão</th><th>Objetivo</th><th>Próximo retorno</th><th>Status</th></tr></thead><tbody>${PAT.map(p=>`<tr class="row" tabindex="0" data-a="open" data-id="${p.id}"><td><b>${p.name}</b></td><td>${p.last}</td><td><div class="bar"><i style="width:${p.adh}%"></i></div>${p.adh}%</td><td>${p.goal}</td><td>${p.ret}</td><td>${statusPill(p.st)}</td></tr>`).join('')}</tbody></table></div>
  <div class="grid2" style="margin-top:12px"><div class="card"><small>Alertas</small>${AL.map(a=>`<div class="kv" style="align-items:center"><span>${a[1]}</span><span><span class="pill ${a[0]==='critical'?'bad':a[0]==='warning'?'warn':''}">${{critical:'crítico',warning:'atenção',info:'info'}[a[0]]}</span></span></div>`).join('')}</div><div class="card"><small>Adesão média da carteira · 8 semanas</small>${lc([68,71,74,70,76,79,82,81],['S1','S2','S3','S4','S5','S6','S7','S8'],'%')}</div></div>
  <div class="row2" style="margin-top:10px"><p class="note" style="margin:0">Clique em um paciente para abrir o prontuário.</p><button class="btn" data-a="newpat">Novo paciente</button></div>`)},
 patients(){const st={q:'',f:'all'};
  const rows=()=>{const r=PAT.filter(p=>(!st.q||p.name.toLowerCase().includes(st.q))&&(st.f==='all'||p.st===st.f));$('#plist').innerHTML=r.length?r.map(p=>`<tr class="row" tabindex="0" data-a="open" data-id="${p.id}"><td><div class="gap8" style="flex-wrap:nowrap"><span class="av">${ini(p.name)}</span><b>${p.name}</b></div></td><td>${p.age} anos</td><td>${p.goal}</td><td>${p.lc}</td><td>${p.ret}</td><td>${statusPill(p.st)}</td></tr>`).join(''):`<tr><td colspan="6">${empty('Nenhum paciente encontrado','Tente outro nome ou limpe o filtro.','<button class="btn sec sm" data-a="clearf">Limpar filtros</button>')}</td></tr>`};
  VIEWS.patients.st=st;VIEWS.patients.rows=rows;
  render(`<div class="row2"><h2>Pacientes</h2><button class="btn" data-a="newpat">Novo paciente</button></div><div class="gap8" style="margin:12px 0"><input class="srch" id="psq" data-i="psearch" placeholder="Buscar por nome" aria-label="Buscar paciente" style="min-width:220px"><span id="pfl" class="gap8">${[['all','Todos'],['ok','Em dia'],['warn','Atenção'],['bad','Sem registro']].map((f,i)=>`<button class="btn sec sm chip" data-a="pfilter" data-f="${f[0]}" ${i?'':'aria-pressed="true"'}>${f[1]}</button>`).join('')}</span></div><div class="card tbl"><table><thead><tr><th>Paciente</th><th>Idade</th><th>Objetivo</th><th>Última consulta</th><th>Próximo retorno</th><th>Status</th></tr></thead><tbody id="plist"></tbody></table></div>`,rows)},
 consults(){const row=(h,n,t,s,b)=>`<div class="review"><div><b>${h} · ${n}</b><div class="note" style="margin:0">${t}</div></div><span class="gap8"><span class="pill ${s[1]}">${s[0]}</span>${b?`<button class="btn sm ${b[1]}" data-a="open" data-id="${b[2]}">${b[0]}</button>`:''}</span></div>`;
  render(`<div class="row2"><h2>Consultas</h2><button class="btn" data-a="toast" data-m="Nova consulta criada em rascunho.">Nova consulta</button></div><div class="grid2" style="margin-top:12px"><div class="card"><small>Hoje · quinta-feira, 01/10</small>${row('08:30','Marina Costa','Retorno · presencial',['Finalizada',''],['Ver','sec',0])}${row('10:00','Rafael Lima','Reavaliação · presencial',['Em andamento','warn'],['Continuar','',1])}${row('14:30','Camila Reis','Retorno · online',['Agendada',''],['Iniciar','',4])}${row('16:00','Pedro Nunes','Inicial · presencial',['Agendada',''],['Iniciar','',3])}</div><div class="card"><small>Próximas</small>${row('02/10 09:00','Joana Alves','Retorno · online',['Agendada',''],null)}${row('18/10 08:30','Marina Costa','Retorno',['Agendada',''],null)}<small class="lbl" style="margin-top:14px">Recentes</small>${row('20/09','Marina Costa','Reavaliação · dieta v3',['Finalizada',''],['Abrir','sec',0])}${row('15/09','Rafael Lima','Retorno',['Finalizada',''],['Abrir','sec',1])}${row('10/09','Joana Alves','Retorno',['Não compareceu','bad'],null)}</div></div>`)},
 agenda(){const D=[['Seg','28/09'],['Ter','29/09'],['Qua','30/09'],['Qui','01/10'],['Sex','02/10'],['Sáb','03/10']],T=3,EV=[[0,1,1,'Rafael Lima','Retorno',''],[0,4,1,'Planejamento','Dietas','o'],[1,0,1,'Camila Reis','Check-in','f'],[1,3,2,'Pedro Nunes','Online','f'],[2,2,1,'Marina Costa','Check-in','f'],[3,0,1,'Marina Costa','Retorno',''],[3,2,1,'Rafael Lima','Reavaliação','o'],[3,6,1,'Camila Reis','Retorno online','f'],[3,8,1,'Pedro Nunes','Inicial',''],[4,1,1,'Joana Alves','Retorno online','f'],[4,4,1,'Planejamento','Dietas','o'],[5,0,3,'Atendimentos','Manhã','o']];
  let h='<div class="h"></div>'+D.map((d,i)=>`<div class="h" ${i===T?'style="color:var(--accent);font-weight:700"':''}>${d[0]} ${d[1]}${i===T?' · hoje':''}</div>`).join('');
  for(let r=0;r<10;r++){h+=`<div class="t">${8+r}h</div>`;for(let c=0;c<6;c++){h+=`<div class="c" ${c===T?'style="background:color-mix(in srgb,var(--mint) 25%,transparent)"':''}>${EV.filter(x=>x[0]===c&&x[1]===r).map(x=>`<div class="ev ${x[5]}" style="height:${x[2]*44-6}px;top:3px" tabindex="0"><b>${x[3]}</b><br>${x[4]}</div>`).join('')}</div>`}}
  render(`<div class="row2"><h2>Agenda · 28/09 a 03/10</h2><span class="gap8"><button class="btn sec sm" aria-label="Semana anterior">‹</button><button class="btn sec sm">Hoje</button><button class="btn sec sm" aria-label="Próxima semana">›</button></span></div><div class="card tbl" style="margin-top:12px;padding:0"><div class="agenda">${h}</div></div><p class="note">Clique em um horário vazio para agendar. Retornos online aparecem com contorno.</p>`)},
 evals(){render(`<div class="row2"><h2>Avaliações</h2><button class="btn" data-a="toast" data-m="Escolha o paciente para iniciar uma avaliação.">Nova avaliação</button></div><div class="card tbl" style="margin-top:12px"><table><thead><tr><th>Data</th><th>Paciente</th><th>Peso</th><th>% gordura</th><th>IMC</th><th>Equação</th><th>Consulta</th></tr></thead><tbody>${PAT.map(p=>{const i=n_(p)-1;return`<tr class="row" tabindex="0" data-a="open" data-id="${p.id}" data-t="Avaliação Física"><td>${p.w.length>1?DATES[i]:'01/10'}</td><td><b>${p.name}</b></td><td>${fmt(p.w[i])} kg</td><td>${fmt(p.f[i])}%</td><td>${fmt(bmi(p,i))}</td><td>Siri</td><td>${CONS[p.id][Math.min(i,CONS[p.id].length-1)][1]}</td></tr>`}).join('')}</tbody></table></div><p class="note">Cada avaliação guarda a equação e a versão usadas. Nada é recalculado depois.</p>`)},
 diets(){const L={published:['Publicada',''],draft:['Rascunho','warn'],finalized:['Finalizada',''],none:['Sem dieta','bad']};
  render(`<div class="row2"><h2>Dietas</h2><button class="btn" data-a="toast" data-m="Escolha um paciente para criar a dieta.">Nova dieta</button></div><div class="grid3" style="margin-top:12px">${PAT.map(p=>{const d=DIETS[p.id];return`<div class="card" tabindex="0" style="cursor:pointer" data-a="open" data-id="${p.id}" data-t="Dieta"><div class="row2"><b style="font-family:var(--display)">${p.name}</b><span class="pill ${L[d.status][1]}">${L[d.status][0]}</span></div><div class="note">${d.status==='none'?'Crie a primeira dieta deste paciente.':'v'+d.version+' · '+fmt(p.vet,0)+' kcal'}</div></div>`}).join('')}</div>`)},
 msgs(){render(`<h2>Mensagens</h2><div class="inbox" style="margin-top:12px"><div class="card" style="padding:6px">${PAT.map((p,i)=>{const c=CHAT[p.id],l=c[c.length-1];return`<div class="conv" tabindex="0" data-a="conv" data-id="${p.id}" ${i?'':'aria-current="true"'}><span class="av">${ini(p.name)}</span><span style="min-width:0;flex:1"><b>${p.name}</b><br><span class="note" style="margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;display:block">${l?(l.audio?'🎤 Áudio '+l.audio:l.t):'Sem mensagens'}</span></span>${i===0&&S.unread?'<span class="pill">1</span>':''}</div>`}).join('')}</div><div class="card" id="chatbox"></div></div>`,()=>chatBox(0,'#chatbox'))},
 reports(){const logo=$('.logo').src;render(`<h2>Relatórios</h2><div class="grid2" style="margin-top:12px"><div class="card"><small>Disponíveis</small>${[['Relatório de Evolução Física','PDF com fotos, medidas, variações e referências'],['Resumo da consulta','Anamnese, avaliação, estratégia e dieta da consulta'],['Adesão mensal da carteira','Check-ins, refeições e alertas por paciente']].map(r=>`<div class="review"><div><b>${r[0]}</b><div class="note" style="margin:0">${r[1]}</div></div><button class="btn sm" data-a="toast" data-m="PDF gerado (exemplo): ${r[0]}.">Gerar PDF</button></div>`).join('')}</div>
  <div class="card"><small>Prévia · Relatório de Evolução Física</small><div class="sheet" style="margin-top:8px"><div class="gap8" style="flex-wrap:nowrap;margin-bottom:10px"><img alt="" style="height:44px" src="${logo}"><div><b style="font-size:14px;color:#2F5238">Relatório de Evolução Física</b><br>BentoNutri · Lucas Bento, Nutricionista</div></div><div><b>Paciente:</b> Marina Costa<br>Inicial 11/08/2026 · Retorno 11/10/2026</div><table style="margin-top:8px"><thead><tr><th>Medida</th><th>Inicial</th><th>Retorno</th><th>Dif.</th></tr></thead><tbody><tr><td>Peso (kg)</td><td>68,4</td><td>66,9</td><td>−1,5</td></tr><tr><td>% gordura</td><td>27,1</td><td>25,3</td><td>−1,8</td></tr><tr><td>Cintura (cm)</td><td>78,0</td><td>75,5</td><td>−2,5</td></tr></tbody></table><div class="gap8" style="margin:10px 0;flex-wrap:nowrap"><div class="fig" style="flex:1;max-height:120px">${SIL(1.06)}</div><div class="fig" style="flex:1;max-height:120px">${SIL(1)}</div></div><div style="color:#666;font-size:10px">Metodologia e referências incluídas no documento completo.</div></div></div></div>`)},
 settings(){const tg=(l,d,on,dis,id)=>`<div class="kv" style="align-items:center"><span>${l}<br><span class="note" style="margin:0">${d}</span></span><button class="tg" role="switch" aria-checked="${on}" aria-label="${l}" ${dis?'disabled':''} data-a="tg"></button></div>`;
  render(`<h2>Configurações</h2><div class="grid2" style="margin-top:12px"><div class="card"><small>Perfil profissional</small><div class="gap8" style="flex-wrap:nowrap;margin:10px 0"><img class="logo" alt="" style="height:56px" src="${$('.logo').src}"><div><b>Lucas Bento</b><div class="note" style="margin:0">Nutricionista · @lucasbentonutri</div></div></div>${kv([['CRN','CRN-6 00000'],['WhatsApp','+55 (83) 99123-8792'],['Instagram','@lucasbentonutri']])}</div>
  <div class="card"><small>Preferências clínicas</small>${kv([['Efeito térmico (TEF) padrão','10%'],['Fator de atividade padrão','Moderado (1,55)'],['Meta de água padrão','3.000 ml']])}${tg('Manter foto original','Guardar também a versão sem compressão',false)}${tg('Salvar rascunhos automaticamente','Continue consultas interrompidas',true)}</div>
  <div class="card"><small>Privacidade e LGPD</small>${tg('Termo de atendimento','Versão 1.0 · exigido no primeiro acesso',true,true)}${tg('Uso clínico de imagens','Versão 1.0',true)}${tg('Uso público de imagens','Versão 1.0 · opcional para o paciente',true)}${tg('Comunicação','Versão 1.0',true)}<p class="note">Cada consentimento é separado e registra versão, data e revogação.</p></div>
  <div class="card"><small>Segurança</small>${kv([['Login','CRN + senha'],['Último acesso','hoje 08:02'],['Sessões ativas','1']])}<div class="gap8" style="margin-top:10px"><button class="btn sec sm" data-a="toast" data-m="Link para alterar a senha enviado ao seu e-mail.">Alterar senha</button><button class="btn sec sm" data-a="toast" data-m="Registro de auditoria exportado (exemplo).">Ver auditoria</button></div></div></div>`)},
 club(){render(`<div class="row2"><h2>BentoNutriClub · moderação</h2><span class="gap8"><button class="btn sec" data-a="newchal">Criar desafio</button><button class="btn" data-a="official">Publicar conteúdo oficial</button></span></div><p class="note" id="clm">Fotos só aparecem com consentimento de uso público. A autoria mostra só o nome preferencial.</p><div id="nfeed" class="stack" style="margin-top:10px"></div>`,()=>feeds())}
};
function open_(id,tab){S.nav='patients';S.pid=+id;S.tab=tab||'Resumo';S.cmp={a:0,b:Math.max(0,n_(PAT[id])-1),angle:0};drawNav();renderPront()}
