/* ================= comunidade (feed compartilhado entre nutricionista e paciente) ================= */
S.posts=[{id:1,a:'Mari',k:'Conquista',t:'Bati a meta de água 7 dias seguidos!',l:12,c:0,st:'v',f:0,img:0,cm:[{a:'Rafa',t:'Parabéns! Constância é tudo.'},{a:'Cami',t:'Inspirador 👏'},{a:'Jo',t:'Vou tentar também.'}]},
 {id:2,a:'Rafa',k:'Receita',t:'Panqueca de banana com aveia: 2 ingredientes, 5 minutos.',l:8,c:0,st:'v',f:0,img:1,cm:[{a:'Mari',t:'Fiz hoje, ficou ótima!'},{a:'BentoNutri',t:'Ótima opção de lanche.'}]},
 {id:3,a:'BentoNutri',k:'Oficial',t:'Dica da semana: planeje o lanche da tarde para evitar exageros no jantar.',l:21,c:0,st:'v',f:1,img:0,cm:[{a:'Jo',t:'Boa dica!'}]}];
S.challenges=[{id:1,title:'7 dias de meta de água',desc:'Bata a meta de água todos os dias da semana.',start:'01/10',end:'07/10',joined:false,done:4}];
S.liked={};S.openCm={};
const pkind=p=>`<span class="pill">${p.k}</span>`;
function postHtml(p,staff){const cm=p.cm.length;
 const act=staff?`<span class="gap8"><button class="btn sec sm" data-a="pfeat" data-id="${p.id}">${p.f?'Remover destaque':'Destacar'}</button><button class="btn sec sm" data-a="phide" data-id="${p.id}">${p.st==='h'?'Reexibir':'Ocultar'}</button><button class="btn sec sm" data-a="pdel" data-id="${p.id}">Excluir</button></span>`:`<span class="gap8"><button class="btn sec sm chip" data-a="plike" data-id="${p.id}" aria-pressed="${!!S.liked[p.id]}">♥ ${p.l+(S.liked[p.id]?1:0)}</button><button class="btn sec sm" data-a="pcm" data-id="${p.id}" aria-expanded="${!!S.openCm[p.id]}">${cm} comentário${cm===1?'':'s'}</button></span>`;
 const cms=S.openCm[p.id]||staff?`<div class="stack" style="margin-top:8px;gap:6px">${p.cm.map((c,i)=>`<div class="sub"><b>${c.a}</b> ${c.t}${staff?` <button class="btn sec sm" style="float:right" data-a="cmdel" data-id="${p.id}" data-i="${i}">Ocultar</button>`:''}</div>`).join('')||'<div class="note">Seja o primeiro a comentar.</div>'}${staff?'':`<div class="gap8" style="flex-wrap:nowrap"><input id="cmi${p.id}" placeholder="Comentar" aria-label="Comentar" style="flex:1"><button class="btn sm" data-a="cmadd" data-id="${p.id}">Enviar</button></div>`}</div>`:'';
 return`<div class="card" style="${p.st==='h'?'opacity:.55':''}"><div class="row2"><b>${p.a}${p.f?' ★':''} ${pkind(p)}${p.st==='h'?' <span class="pill warn">oculta</span>':''}</b></div><p style="margin:8px 0">${p.t}</p>${p.img?`<div class="fig wide" style="margin-bottom:8px"><span class="cap">Foto publicada · consentimento público ativo</span></div>`:''}${act}${cms}</div>`}
const chalHtml=(c,staff)=>`<div class="card" style="border-color:var(--accent)"><div class="row2"><b style="font-family:var(--display)">🏁 Desafio: ${c.title}</b><span class="pill">${c.start} a ${c.end}</span></div><p style="margin:6px 0">${c.desc}</p>${staff?`<div class="note">${c.joined?4:3} participantes</div>`:`<div class="bar" style="margin:6px 0"><i style="width:${c.joined?Math.round(c.done/7*100):0}%"></i></div><div class="row2"><span class="note" style="margin:0">${c.joined?c.done+' de 7 dias':'Participe e acompanhe seu progresso'}</span><button class="btn sm ${c.joined?'sec':''}" data-a="chjoin" data-id="${c.id}">${c.joined?'Participando ✓':'Participar'}</button></div>`}</div>`;
function feeds(){const v=S.posts.filter(p=>p.st!=='d');
 const pf=$('#pfeed');if(pf){const vis=v.filter(p=>p.st==='v');pf.innerHTML=S.challenges.map(c=>chalHtml(c,false)).join('')+(vis.length?vis.map(p=>postHtml(p,false)).join(''):empty('Ainda não há publicações','Compartilhe a primeira conquista ou receita com a comunidade.'))}
 const nf=$('#nfeed');if(nf)nf.innerHTML=S.challenges.map(c=>chalHtml(c,true)).join('')+(v.length?v.map(p=>postHtml(p,true)).join(''):empty('Nenhuma publicação','Publique um conteúdo oficial para iniciar a comunidade.'))}
