/* ================= prontuário ================= */
const TABS=['Resumo','Histórico','Anamnese','Avaliação Física','Fotometria','Composição Corporal','Gasto Energético','Dieta','Check-ins','Refeições','Mensagens','Evolução'];
const cur=()=>PAT[S.pid];
function renderPront(){const p=cur(),c=CONS[p.id].find(x=>x[3]==='draft');
 render(`<div class="row2"><button class="btn sec" data-a="nav" data-k="patients">← Pacientes</button>${c?'<span class="pill">Consulta de '+c[0]+' · rascunho salvo automaticamente</span>':'<span class="pill mut">Sem consulta em andamento</span>'}</div>
 <div class="gap8" style="margin-top:12px;flex-wrap:nowrap"><span class="av" style="width:46px;height:46px;font-size:16px">${ini(p.name)}</span><div><h2>${p.name}</h2><div class="note" style="margin:0">${p.age} anos na avaliação · ${p.goal} · ${p.sex==='F'?'feminino':'masculino'} · Nutricionista: Lucas Bento</div></div></div>
 <div class="tabs" role="tablist" id="tabs">${TABS.map(t=>`<button role="tab" data-a="tab" data-t="${t}" aria-selected="${t===S.tab}">${t}</button>`).join('')}</div><div id="pane"></div>`,()=>setTab(S.tab),false)}
function setTab(t,load=true){S.tab=t;$$('#tabs button').forEach(b=>{const on=b.dataset.t===t;b.setAttribute('aria-selected',on);if(on)b.scrollIntoView({inline:'nearest',block:'nearest'})});const pane=$('#pane'),r=TAB[t](cur());
 const put=()=>{pane.innerHTML=r.html;r.after&&r.after()};if(!load){put();return}pane.innerHTML=skel(3);clearTimeout(setTab.t);setTab.t=setTimeout(put,140)}
const goTab=t=>setTab(t);
const emptyCTA=(t,d,b,a)=>empty(t,d,`<button class="btn sm" data-a="${a}" data-t="${b[1]||''}">${b[0]}</button>`);
const sx=(p,i)=>1+(p.w[i]-p.w[0])/p.w[0]*2.5;
const TAB={
 'Resumo':p=>{const L=n_(p)-1,d=DIETS[p.id],c=CONS[p.id];if(n_(p)<2&&d.status==='none')return{html:`<div class="grid2"><div class="card"><small>Primeira consulta</small>${kv([['Peso',fmt(p.w[0])+' kg'],['Altura',p.h+' cm'],['IMC',fmt(bmi(p))+' · '+bmiC(bmi(p))]])}<p class="note">Faltam anamnese, composição corporal e estratégia calórica.</p></div><div class="card">${empty('Prontuário em construção','Siga a ordem: anamnese → avaliação → energia → dieta.',`<button class="btn sm" data-a="tab" data-t="Anamnese">Começar pela anamnese</button>`)}</div></div>`};
  return{html:`<div class="grid2"><div class="card"><small>Evolução (${DATES[0]} → ${DATES[L]})</small>${kv([['Peso',fmt(p.w[0])+' → '+fmt(p.w[L])+' kg'],['% gordura',fmt(p.f[0])+' → '+fmt(p.f[L])+' %'],['Massa magra',fmt(mlg(p,0))+' → '+fmt(mlg(p,L))+' kg'],['Cintura',fmt(p.wa[0])+' → '+fmt(p.wa[L])+' cm']])}</div>
  <div class="card"><small>Estratégia vigente</small>${p.vet?kv([['GET',fmt(p.vet/(p.id===1?1.1:0.9),0)+' kcal'],['Estratégia',p.id===1?'Superávit +10%':'Déficit −10%'],['VET',fmt(p.vet,0)+' kcal'],['Dieta','v'+d.version+' · '+{published:'publicada',draft:'rascunho',finalized:'finalizada'}[d.status]]]):empty('Sem estratégia','Calcule o gasto energético para definir o VET.')}</div>
  <div class="card"><small>Próximas ações</small><div class="stack" style="margin-top:8px"><button class="btn sec" data-a="tab" data-t="Avaliação Física">Registrar avaliação física</button><button class="btn sec" data-a="tab" data-t="Dieta">${d.status==='none'?'Criar dieta':'Abrir dieta'}</button><button class="btn sec" data-a="tab" data-t="Mensagens">Responder mensagens</button></div></div>
  <div class="card"><small>Consultas</small>${c.map(x=>`<div class="kv"><span>${x[0]} · ${x[1]}</span><span>${x[2]}</span></div>`).join('')}</div></div>`}},
 'Histórico':p=>{const L={finalized:['Finalizada',''],amended:['Emendada','warn'],draft:['Em andamento','warn'],sched:['Agendada','mut'],bad:['Não compareceu','bad']};
  return{html:`<div class="card"><small>Linha do tempo de consultas</small>${CONS[p.id].map((x,i)=>`<div class="review"><div><b>${x[0]} · ${x[1]}</b><div class="note" style="margin:0">${x[3]==='amended'?'Emendada por Lucas Bento · motivo: "perímetro corrigido"':x[3]==='finalized'?'Finalizada · versão 1 · dados preservados':x[3]==='draft'?'Continue de onde parou':x[3]==='sched'?'Aguardando atendimento':'Registrado como não comparecimento'}</div></div><span class="gap8"><span class="pill ${L[x[3]][1]}">${L[x[3]][0]}</span>${x[3]==='finalized'?`<button class="btn sec sm" data-a="amend" data-i="${i}">Emendar</button>`:''}${x[3]==='amended'?`<button class="btn sec sm" data-a="orig" data-i="${i}">Ver original</button>`:''}${x[3]==='draft'?`<button class="btn sm" data-a="finalize" data-i="${i}">Finalizar consulta</button>`:''}</span></div>`).join('')}<p class="note">Consulta finalizada não é sobrescrita: a emenda guarda o valor original, quem alterou, quando e por quê. Tudo entra na auditoria.</p></div>`}},
 'Anamnese':p=>({html:`<div class="grid2"><div class="card"><small>Relato (texto ou áudio transcrito)</small><textarea id="at" rows="7" style="width:100%;margin-top:8px">${p.id===0?'Dorme às 23h e acorda às 6h30. Acorda 2 vezes de noite. É alérgica a camarão. Bebe 2,5 litros de água. Tem refluxo ocasional após o jantar. Usa creatina 3 g por dia. Bristol 4.':''}</textarea><div class="row2" style="margin-top:8px"><span class="gap8"><button class="btn" data-a="extract">Extrair dados</button><span class="recbox" data-id="anam" data-done="anam"><button class="btn sec" data-a="recstart">🎤 Gravar áudio</button></span></span><span class="note" style="margin:0">Extração local: nada sai do sistema</span></div></div><div class="card" id="ao"><small>Dados extraídos da anamnese</small>${empty('Nada extraído ainda','Cole o relato ou grave um áudio e clique em "Extrair dados".')}</div></div>`}),
 'Avaliação Física':p=>{const L=n_(p)-1,pairs=[['Antebraço',28.4,27.9],['Bíceps relaxado',32.1,31.4],['Bíceps contraído',34.6,34.0],['Coxa proximal',58.9,58.2],['Coxa medial',54.6,54.4],['Coxa distal',42.5,41.9],['Panturrilha',37.5,36.6]].map(r=>[r[0],r[1]+(p.id%3)*.4,r[2]+(p.id%2)*.3]);
  const num=(id,l,v)=>`<label>${l}<br><input class="as" id="${id}" type="number" step="0.1" value="${v}" style="width:100%" data-i="assess"></label>`;
  return{html:`<div class="grid2"><div class="card"><small>Medidas (cm · precisão 0,1)</small><div class="grid2" style="grid-template-columns:1fr 1fr;margin-top:8px">${num('aw','Peso (kg)',p.w[L])}${num('ah','Altura (cm)',p.h)}${num('an','Pescoço',37.2)}${num('as_','Ombro',112)}${num('ac_','Tórax',92)}${num('ac','Cintura',p.wa[L])}${num('ab','Abdômen',p.wa[L]+4)}${num('aq','Quadril',p.hip)}</div></div><div class="card" id="ares"></div></div>
  <div class="card tbl" style="margin-top:12px"><small>Perimetria bilateral</small><table style="min-width:420px"><thead><tr><th>Medida</th><th>Direito</th><th>Esquerdo</th><th>Assimetria |D − E|</th></tr></thead><tbody>${pairs.map((r,i)=>`<tr><td>${r[0]}</td><td><input class="pr" data-i="assess" data-k="${i}" type="number" step="0.1" value="${r[1].toFixed(1)}" style="width:84px" aria-label="${r[0]} direito"></td><td><input class="pl" data-i="assess" data-k="${i}" type="number" step="0.1" value="${r[2].toFixed(1)}" style="width:84px" aria-label="${r[0]} esquerdo"></td><td id="asy${i}"></td></tr>`).join('')}</tbody></table><p class="note">A assimetria é calculada automaticamente. Valores a partir de 0,8 cm ficam destacados.</p></div>`,after:()=>I.assess()}},
 'Composição Corporal':p=>{const L=n_(p)-1;return{html:`<div class="grid2"><div class="card"><small>Plicometria (mm · precisão 0,1)</small><label style="display:block;margin-top:8px">Protocolo<br><select id="skp" style="width:100%" data-i="skp">${Object.entries(PROT).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></label><div id="skf" class="grid2" style="grid-template-columns:1fr 1fr;margin-top:8px"></div><div class="kv" style="margin-top:8px"><span>Σ dobras</span><span id="sks">0,0 mm</span></div><button class="btn" data-a="skcalc" style="margin-top:8px">Calcular composição</button><p class="note" id="skm">Os campos mudam conforme o protocolo escolhido.</p></div>
  <div class="card"><small>%G a partir de densidade corporal conhecida</small><label style="display:block;margin-top:8px">Db (g/cm³)<br><input id="db" type="number" step="0.001" value="${(1.1-p.f[L]/100*0.46).toFixed(3)}" style="width:100%" data-i="dens"></label><label style="display:block;margin-top:6px">Equação<br><select id="eq" style="width:100%" data-i="dens"><option value="siri">Siri</option><option value="brozek">Brožek</option></select></label><div id="dres" style="margin-top:8px"></div></div></div>`,after:()=>{I.skp();I.dens()}}},
 'Gasto Energético':p=>({html:energyHtml(p),after:()=>I.energy()}),
 'Dieta':p=>dietTab(p),
 'Check-ins':p=>{const ck=CK(p);return{html:`<div class="grid2"><div class="card"><small>Última semana</small>${ck.map(c=>`<div class="kv" style="align-items:center"><span>${c.d}<br><span class="note" style="margin:0">${c.tr?'Treinou · '+c.m+' '+c.min+' min':'Não treinou'}</span></span><span class="gap8" style="flex-wrap:nowrap"><span class="water" style="width:84px;gap:3px">${Array.from({length:6},(_,i)=>`<i class="${i<c.w/500?'f':''}" style="height:12px"></i>`).join('')}</span>${c.adh}%</span></div>`).join('')}<p class="note">Adesão do dia = refeições registradas ÷ planejadas.</p></div>
  <div class="card"><small>Responder ao check-in</small><div class="gap8" style="margin:8px 0">${BADGES.map(b=>`<button class="btn sec sm chip" data-a="badge" data-b="${b}" aria-pressed="false">${b}</button>`).join('')}</div><textarea id="fbt" rows="2" style="width:100%" placeholder="Mensagem curta (texto)"></textarea><div class="gap8" style="margin-top:8px"><span class="recbox" data-id="fb" data-done="fb"><button class="btn sec sm" data-a="recstart">🎤 Gravar áudio</button></span><span id="fba" class="pill mut" hidden></span></div><div class="gap8" style="margin-top:8px"><button class="btn" data-a="fbsend">Enviar feedback</button><span class="note" id="fbm" style="margin:0"></span></div></div></div>`}},
 'Refeições':p=>({html:`<div class="grid3">${MEALLOG.map((r,i)=>`<div class="card"><div class="fig" style="aspect-ratio:4/3"><span class="cap">Foto (privada)</span></div><div class="kv" style="margin-top:8px"><span>${r[0]}</span><span></span></div><div class="note">Antes: ${r[1]} · Depois: ${r[2]}</div><button class="btn sec sm" style="margin-top:6px" data-a="mreply" data-i="${i}">Responder</button></div>`).join('')}</div>`}),
 'Mensagens':p=>({html:`<div class="card" style="max-width:560px" id="chatbox"></div>`,after:()=>chatBox(p.id,'#chatbox')}),
 'Fotometria':p=>photoTab(p),
 'Evolução':p=>evoTab(p),
};
const BADGES=['Boa consistência','Excelente hidratação','Treino concluído','Boa escolha','Semana consistente'];
const PROT={jp7:['Jackson & Pollock 7 dobras',['Peitoral','Axilar média','Tríceps','Subescapular','Abdominal','Supra-ilíaca','Coxa']],jp3:['Jackson & Pollock 3 dobras',['Tríceps','Supra-ilíaca','Coxa']],petroski4:['Petroski 4 dobras',['Subescapular','Tríceps','Supra-ilíaca','Panturrilha']],faulkner4:['Faulkner 4 dobras',['Tríceps','Subescapular','Supra-ilíaca','Abdominal']],durnin4:['Durnin & Womersley 4 dobras',['Bíceps','Tríceps','Subescapular','Supra-ilíaca']],guedes3:['Guedes 3 dobras',['Tríceps','Supra-ilíaca','Abdominal']]};

/* ---- gasto energético (equações e metodologia conforme o motor clínico) ---- */
function energyHtml(p){const o=(a)=>a.map(x=>`<option value="${x[0]}" ${x[2]?'selected':''}>${x[1]}</option>`).join('');
 return`<div class="grid2"><div class="card"><small>Parâmetros · ${p.sex==='F'?'feminino':'masculino'}, ${p.age} anos, ${fmt(p.w[n_(p)-1])} kg, ${p.h} cm, MLG ${fmt(mlg(p))} kg</small>
 <label style="display:block;margin-top:8px">Equação<br><select id="e1" style="width:100%" data-i="energy">${o([['mif','Mifflin-St Jeor',1],['hb','Harris-Benedict revisada'],['km','Katch-McArdle (usa MLG)'],['cu','Cunningham (usa MLG)'],['fao','FAO/OMS']])}</select></label>
 <label style="display:block;margin-top:6px">Metodologia do GET<br><select id="e0" style="width:100%" data-i="energy">${o([['fat','Fatorial: TMB × fator de atividade',1],['met','Detalhado: TMB + exercício (MET) + TEF']])}</select></label>
 <div id="e2w"><label style="display:block;margin-top:6px">Fator de atividade<br><select id="e2" style="width:100%" data-i="energy">${[[1.2,'Sedentário 1,20'],[1.375,'Levemente ativo 1,375'],[1.55,'Moderado 1,55'],[1.725,'Muito ativo 1,725'],[1.9,'Extremamente ativo 1,90']].map(x=>`<option value="${x[0]}" ${x[0]===p.fa?'selected':''}>${x[1]}</option>`).join('')}</select></label></div>
 <div id="e3w" hidden><div class="tbl"><table style="min-width:360px"><thead><tr><th>Atividade</th><th>MET</th><th>Min</th><th>Vezes/sem</th></tr></thead><tbody><tr><td>Musculação</td><td><input class="mt" data-i="energy" type="number" step=".1" value="5" style="width:64px"></td><td><input class="mm" data-i="energy" type="number" value="60" style="width:64px"></td><td><input class="mf" data-i="energy" type="number" value="4" style="width:60px"></td></tr><tr><td>Corrida</td><td><input class="mt" data-i="energy" type="number" step=".1" value="9.8" style="width:64px"></td><td><input class="mm" data-i="energy" type="number" value="40" style="width:64px"></td><td><input class="mf" data-i="energy" type="number" value="2" style="width:60px"></td></tr></tbody></table></div><label style="display:block;margin-top:6px">Efeito térmico dos alimentos (%)<br><input id="etef" type="number" value="10" min="0" max="30" style="width:90px" data-i="energy"></label><p class="note">O MET é informado por você. Esta metodologia não usa fator de atividade.</p></div>
 <label style="display:block;margin-top:6px">Estratégia<br><select id="e4" style="width:100%" data-i="energy">${[[-30,'Déficit −30%'],[-20,'Déficit −20%'],[-10,'Déficit −10%',p.id!==1],[0,'Manutenção'],[10,'Superávit +10%',p.id===1],[15,'Superávit +15%'],[20,'Superávit +20%']].map(x=>`<option value="${x[0]}" ${x[2]?'selected':''}>${x[1]}</option>`).join('')}</select></label>
 <label style="display:block;margin-top:6px">Macronutrientes<br><select id="e5" style="width:100%" data-i="energy"><option value="pct">Por percentual</option><option value="gkg">Por g/kg</option></select></label>
 <div id="e5a" class="gap8" style="margin-top:6px"><label>P %<br><input id="mp" type="number" value="30" style="width:70px" data-i="energy"></label><label>C %<br><input id="mc" type="number" value="45" style="width:70px" data-i="energy"></label><label>G %<br><input id="mf2" type="number" value="25" style="width:70px" data-i="energy"></label></div><div id="e5b" class="gap8" style="margin-top:6px" hidden><label>Proteína g/kg<br><input id="gp" type="number" step=".1" value="2" style="width:80px" data-i="energy"></label><label>Gordura g/kg<br><input id="gf" type="number" step=".1" value=".9" style="width:80px" data-i="energy"></label><span class="note">Carboidrato = restante</span></div></div>
 <div class="card" id="eres"></div></div>`}
