/* ================= cálculos ao vivo (mesmas fórmulas do motor clínico) ================= */
const I={
 psearch(el){VIEWS.patients.st.q=el.value.toLowerCase();VIEWS.patients.rows()},
 assess(){const g=id=>parseFloat($('#'+id).value),w=g('aw'),h=g('ah'),c=g('ac'),q=g('aq'),o=$('#ares');
  $$('.pr').forEach(r=>{const k=r.dataset.k,l=$$('.pl')[k],a=Math.abs(parseFloat(r.value)-parseFloat(l.value));$('#asy'+k).innerHTML=isNaN(a)?'—':`<span class="${a>=.8?'asym':''}">${fmt(a)} cm</span>`});
  if(!(w>0&&h>0&&c>0&&q>0)){o.innerHTML='<small>Resultados derivados</small><div class="banner bad" role="alert" style="margin-top:8px">Preencha peso, altura, cintura e quadril com valores válidos.</div>';return}
  const b=w/((h/100)**2);o.innerHTML='<small>Resultados derivados</small>'+kv([['IMC',fmt(b)+' kg/m² · '+bmiC(b)],['RCQ',fmt(c/q,2)],['RCEst',fmt(c/h,2)]])+'<p class="note">Classificação: OMS adultos, v1.0. Cada resultado guarda a fórmula e a versão usadas.</p>'},
 skp(){const sel=$('#skp'),p=PROT[sel.value];$('#skf').innerHTML=p[1].map(n=>`<label>${n}<br><input class="sk" type="number" step="0.1" min="0" placeholder="0,0" style="width:100%" data-i="sksum"></label>`).join('');I.sksum()},
 sksum(){const t=$$('.sk').reduce((a,b)=>a+(+b.value||0),0);$('#sks').textContent=fmt(t)+' mm'},
 dens(){const p=cur(),w=p.w[n_(p)-1],db=parseFloat($('#db').value),e=$('#eq').value,o=$('#dres');if(!(db>.9&&db<1.2)){o.innerHTML='<div class="banner bad" role="alert">Densidade fora do intervalo plausível (0,9 a 1,2).</div>';return}
  const g=e==='siri'?(4.95/db-4.5)*100:(4.57/db-4.142)*100;o.innerHTML=kv([['% gordura',fmt(g)+' %'],['Massa gorda ('+fmt(w)+' kg)',fmt(w*g/100)+' kg'],['Massa livre de gordura',fmt(w*(1-g/100))+' kg']])+`<p class="note">Equação: ${e==='siri'?'Siri (1961)':'Brožek (1963)'} · v1.0</p>`},
 energy(){const p=cur(),L=n_(p)-1,w=p.w[L],m=mlg(p),g=id=>$('#'+id),eq=g('e1').value,meth=g('e0').value,fa=+g('e2').value,st=+g('e4').value,mode=g('e5').value;
  g('e2w').hidden=meth!=='fat';g('e3w').hidden=meth!=='met';g('e5a').hidden=mode!=='pct';g('e5b').hidden=mode!=='gkg';const o=g('eres');
  if(eq==='fao'){o.innerHTML='<small>Resultado</small><div class="banner warn" style="margin-top:8px"><span><b>FAO/OMS em validação científica.</b> Os coeficientes por faixa etária serão liberados após a conferência na referência original.</span></div>';return}
  const t=eq==='mif'?10*w+6.25*p.h-5*p.age+(p.sex==='M'?5:-161):eq==='hb'?(p.sex==='M'?88.362+13.397*w+4.799*p.h-5.677*p.age:447.593+9.247*w+3.098*p.h-4.33*p.age):eq==='km'?370+21.6*m:500+22*m;
  let get,lines;if(meth==='fat'){get=t*fa;lines=[['Fator de atividade',fmt(fa,3).replace(/0$/,'')],['GET = TMB × FA',fmt(get,0)+' kcal']]}
  else{let wk=0;$$('.mt').forEach((x,i)=>{wk+=(+x.value||0)*w*((+$$('.mm')[i].value||0)/60)*(+$$('.mf')[i].value||0)});const ex=wk/7,tef=(+g('etef').value||0)/100,base=t+ex;get=base+base*tef;lines=[['Exercício (MET)',fmt(ex,0)+' kcal/dia'],['TEF ('+fmt(tef*100,0)+'%)',fmt(base*tef,0)+' kcal'],['GET',fmt(get,0)+' kcal']]}
  const vet=get*(1+st/100);let P,G,C;
  if(mode==='pct'){const a=+g('mp').value,b=+g('mc').value,c=+g('mf2').value;if(Math.abs(a+b+c-100)>.01){o.innerHTML='<small>Resultado</small><div class="banner bad" role="alert" style="margin-top:8px">Os percentuais devem somar 100% (hoje somam '+fmt(a+b+c,0)+'%).</div>';return}P=vet*a/100/4;C=vet*b/100/4;G=vet*c/100/9}
  else{P=+g('gp').value*w;G=+g('gf').value*w;C=(vet-P*4-G*9)/4;if(C<0){o.innerHTML='<small>Resultado</small><div class="banner bad" role="alert" style="margin-top:8px">Proteína e gordura excedem o VET.</div>';return}}
  const kc=P*4+C*4+G*9,dev=(kc-vet)/vet*100;
  o.innerHTML='<small>Resultado reproduzível</small>'+kv([['TMB',fmt(t,0)+' kcal']].concat(lines,[['Estratégia',(st>0?'+':'')+st+'%'],['VET','<b>'+fmt(vet,0)+' kcal</b>']]))+'<small class="lbl" style="margin-top:12px">Macronutrientes</small>'+kv([['Proteína',fmt(P,0)+' g · '+fmt(P/w,1)+' g/kg'],['Carboidrato',fmt(C,0)+' g'],['Gordura',fmt(G,0)+' g · '+fmt(G/w,1)+' g/kg'],['Conferência com o VET',Math.abs(dev)<=2?'<span class="pill">coerente</span>':'<span class="pill warn">'+fmt(dev)+'% de diferença</span>']])+`<p class="note">Equação e versão registradas (v1.0). ${meth==='fat'?'TEF já incluído no fator.':'Metodologia detalhada: não usa fator de atividade.'}</p>`}
};
/* ================= chat e áudio ================= */
const REC={};
function audHtml(sec,mine){return`<div class="aud"><button class="btn sec sm" data-a="play" data-s="${sec}" aria-label="Reproduzir áudio" style="min-height:30px;padding:2px 10px;${mine?'color:inherit;border-color:currentColor':''}">▶</button><span class="tr"><i></i></span><span>0:${String(sec).padStart(2,'0')}</span></div>`}
function chatBox(pid,sel,asPatient){const c=CHAT[pid],box=$(sel);if(!box)return;const mine=asPatient?0:1;
 box.innerHTML=`${asPatient?'':`<small class="lbl">${PAT[pid].name}</small>`}<div class="stack" style="gap:8px;margin:10px 0;min-height:60px">${c.length?c.map(m=>`<div class="bub ${m.me===mine?'me':''}">${m.audio?audHtml(m.audio,m.me===mine):m.t}<small>${m.h}${m.me===mine?' · '+(m.read?'lida':'enviada'):''}</small></div>`).join(''):empty('Nenhuma mensagem','Comece a conversa com '+(asPatient?'seu nutricionista':PAT[pid].name.split(' ')[0])+'.')}</div><div class="gap8" style="flex-wrap:nowrap"><input id="ci" placeholder="${asPatient?'Escreva uma mensagem':'Responder'}" aria-label="Mensagem" style="flex:1;min-width:0"><span class="recbox" data-id="chat" data-done="chat" data-pid="${pid}" data-pat="${asPatient?1:0}"><button class="btn sec" data-a="recstart" aria-label="Gravar áudio">🎤</button></span><button class="btn" data-a="send" data-pid="${pid}" data-pat="${asPatient?1:0}">Enviar</button></div>`}
const DONE={
 anam(sec){const t=$('#at');if(t)t.value=(t.value?t.value+' ':'')+'Dorme às 23h e acorda às 6h30. Bebe 2 litros de água. Tem refluxo ocasional. Usa whey 30 g por dia.';toast('Transcrição pronta. Revise o texto antes de extrair.')},
 chat(sec,box){const pid=+box.dataset.pid,pat=box.dataset.pat==='1';CHAT[pid].push({me:pat?0:1,audio:Math.max(sec,2),h:'agora'});chatBox(pid,pat?'#pchat':'#chatbox',pat)},
 fb(sec){const a=$('#fba');if(a){a.hidden=false;a.textContent='🎤 Áudio de 0:'+String(Math.max(sec,3)).padStart(2,'0')+' anexado'}}
};
/* ================= comparador, fotometria e evolução ================= */
const ANG=['Frente','Perfil direito','Perfil esquerdo','Costas'];
function cmpControls(p){const o=(v)=>p.w.map((_,i)=>`<option value="${i}" ${i===v?'selected':''}>${DATES[i]}/2026</option>`).join('');
 return`<div class="gap8"><label>Inicial<br><select id="ca" data-i="cmp">${o(S.cmp.a)}</select></label><label>Retorno<br><select id="cb" data-i="cmp">${o(S.cmp.b)}</select></label></div>`}
function cmpTable(p){const a=S.cmp.a,b=S.cmp.b,rows=[['Peso','kg',p.w[a],p.w[b]],['% gordura','%',p.f[a],p.f[b]],['Massa gorda','kg',mg(p,a),mg(p,b)],['Massa livre de gordura','kg',mlg(p,a),mlg(p,b)],['Cintura','cm',p.wa[a],p.wa[b]],['RCQ','',p.wa[a]/p.hip,p.wa[b]/p.hip],['RCEst','',p.wa[a]/p.h,p.wa[b]/p.h]];
 return`<div class="tbl"><table style="min-width:440px"><thead><tr><th>Medida</th><th>${DATES[a]}</th><th>${DATES[b]}</th><th>Dif.</th><th>Dif. %</th></tr></thead><tbody>${rows.map(r=>{const d=r[3]-r[2],dg=r[1]===''?2:1;return`<tr><td>${r[0]}${r[1]?' ('+r[1]+')':''}</td><td>${fmt(r[2],dg)}</td><td>${fmt(r[3],dg)}</td><td>${d>0?'+':''}${fmt(d,dg)}</td><td>${d>0?'+':''}${fmt(d/r[2]*100)}%</td></tr>`}).join('')}</tbody></table></div>`}
const cmpTwo=(p,i)=>`<div class="grid2" style="grid-template-columns:1fr 1fr"><div><div class="fig">${SIL(sx(p,S.cmp.a))}${S.grid?GRID:''}<span class="cap">Inicial · ${DATES[S.cmp.a]}</span></div></div><div><div class="fig">${SIL(sx(p,S.cmp.b))}${S.grid?GRID:''}<span class="cap">Retorno · ${DATES[S.cmp.b]}</span></div></div></div>`;
function photoTab(p){const ok=S.consent.clin,L=n_(p)-1;
 const banner=ok?`<div class="banner ok"><span><b>Consentimento de imagem:</b> uso clínico aceito (v1.0, 11/08/2026) · uso público não autorizado</span></div>`:`<div class="banner bad"><span><b>Uso clínico de imagens revogado pelo paciente.</b> Novas fotos não podem ser salvas.</span></div>`;
 const up=`<div class="card"><div class="row2"><b>Adicionar fotos</b><span class="gap8"><button class="btn sec sm" data-a="upl" ${ok?'':'disabled'}>📷 Câmera</button><button class="btn sec sm" data-a="upl" ${ok?'':'disabled'}>🖼 Galeria</button></span></div><div style="border:2px dashed var(--line);border-radius:12px;padding:16px;text-align:center;margin-top:10px;color:var(--muted)">Arraste as fotos aqui<br><span class="note">JPEG ou WebP · reduzidas e comprimidas antes do envio (máx. 1600 px)</span></div><div id="upp" class="stack" style="margin-top:8px"></div></div>`;
 const slots=p.id===3&&!S.pedroPhotos?empty('Nenhuma foto ainda','Peça as quatro fotos padronizadas: frente, perfil direito, perfil esquerdo e costas.'):`<div class="grid2" style="grid-template-columns:repeat(auto-fit,minmax(130px,1fr))">${ANG.map(a=>`<div class="fig">${SIL(sx(p,L))}${GRID}<span class="cap">${a}</span></div>`).join('')}</div><p class="note">A grade ajuda a padronizar o enquadramento. Não faz diagnóstico postural. Bucket privado, URL assinada de 5 minutos e cada acesso é auditado.</p>`;
 const cmp=n_(p)<2?`<div class="card">${empty('Comparação indisponível','São necessárias duas consultas com fotos. Agende a reavaliação.')}</div>`:`<div class="card"><div class="row2"><b style="font-family:var(--display)">Evolução corporal</b>${cmpControls(p)}</div><div class="gap8" style="margin:10px 0"><label class="gap8"><input type="checkbox" id="gridck" data-i="grid" ${S.grid?'checked':''} style="min-height:0"> Mostrar grade</label><label>Ângulo<select id="cang" data-i="cmp">${ANG.map((a,i)=>`<option value="${i}" ${i===S.cmp.angle?'selected':''}>${a}</option>`).join('')}</select></label></div><div class="grid2"><div><small class="lbl">Lado a lado · ${ANG[S.cmp.angle]}</small>${cmpTwo(p)}</div><div><small class="lbl">Antes ← → Depois</small><div class="sl" id="sl" style="margin-top:6px"><div class="a">${SIL(sx(p,S.cmp.a))}</div><div class="b" id="slb" style="clip-path:inset(0 0 0 50%)">${SIL(sx(p,S.cmp.b))}</div><i id="sli" style="left:50%"></i></div><input id="slr" type="range" min="0" max="100" value="50" style="width:100%;max-width:300px;margin-top:8px" aria-label="Comparar antes e depois" data-i="slider"></div></div></div>`;
 return{html:`<div class="stack">${banner}<div class="grid2">${up}<div class="card"><small>Consulta atual · 4 ângulos</small><div style="margin-top:8px">${slots}</div></div></div>${cmp}</div>`}}
function evoTab(p){if(n_(p)<2)return{html:`<div class="card">${empty('Ainda não há evolução','A evolução aparece a partir da segunda consulta. Agende a reavaliação para comparar.','<button class="btn sm" data-a="toast" data-m="Reavaliação agendada para 18/10.">Agendar reavaliação</button>')}</div>`};
 const ch=[['Peso',p.w,'kg'],['% gordura',p.f,'%'],['Cintura',p.wa,'cm'],['IMC',p.w.map((_,i)=>bmi(p,i)),'']];
 return{html:`<div class="grid2">${ch.map(c=>{const d=c[1][c[1].length-1]-c[1][0];return`<div class="card"><small>${c[0]}</small>${lc(c[1],DATES.slice(0,c[1].length),c[2])}${kv([['Variação',(d>0?'+':'')+fmt(d,c[0]==='IMC'?2:1)+' '+c[2]+' ('+(d>0?'+':'')+fmt(d/c[1][0]*100)+'%)']])}</div>`}).join('')}</div><div class="card" style="margin-top:12px"><div class="row2"><b style="font-family:var(--display)">Comparar consultas</b>${cmpControls(p)}</div><div id="ctab" style="margin-top:8px">${cmpTable(p)}</div><p class="note">Cada ponto vem de uma consulta finalizada, com a fórmula e a versão usadas na época.</p></div>`}}
Object.assign(I,{
 cmp(){S.cmp.a=+$('#ca').value;S.cmp.b=+$('#cb').value;const g=$('#cang');if(g)S.cmp.angle=+g.value;setTab(S.tab,false)},
 grid(el){S.grid=el.checked;setTab(S.tab,false)},
 slider(el){const v=el.value;$('#slb').style.clipPath='inset(0 0 0 '+v+'%)';$('#sli').style.left=v+'%'}
});
