/* ================= login, primeiro acesso e app do paciente ================= */
S.onboarded=false;S.cdate={clin:'11/08/2026',pub:null,comm:'11/08/2026'};S.pstate={trained:null,min:'',mod:'Musculação'};S.mealSel={mt:1,fb:null,fa:null};S.attach=false;
const phMask=v=>{let d=v.replace(/\D/g,'');if(d.startsWith('55'))d=d.slice(2);d=d.slice(0,11);if(!d)return'';const r=d.slice(2),c=r.length>8?5:4;return'+55 ('+d.slice(0,2)+(d.length>2?') '+r.slice(0,c)+(r.length>c?'-'+r.slice(c):''):'')};
function drawLogin(){const logo=$('.logo').src;$('#login').innerHTML=`<div class="phone" style="gap:16px"><div style="text-align:center"><img alt="Lucas Bento Nutricionista" style="height:130px" src="${LOGO_FULL}"></div>
 <div class="seg" role="tablist" style="width:100%"><button role="tab" data-a="lmode" data-m="p" id="lmp" aria-pressed="true" style="flex:1;text-align:center">Paciente</button><button role="tab" data-a="lmode" data-m="n" id="lmn" aria-pressed="false" style="flex:1;text-align:center">Nutricionista</button></div>
 <form id="lfp" novalidate class="stack" style="gap:10px"><div id="ls1" class="stack" style="gap:10px"><label>Telefone<br><input id="lph" inputmode="tel" data-i="phone" placeholder="+55 (83) 99999-9999" style="width:100%;min-height:44px" autocomplete="tel"></label><button class="btn" type="submit" style="min-height:44px">Enviar código por SMS</button></div>
 <div id="ls2" class="stack" style="gap:10px" hidden><p class="note" id="lsent" style="margin:0"></p><label>Código<br><input id="lcode" inputmode="numeric" maxlength="6" style="width:100%;min-height:44px;letter-spacing:.4em" autocomplete="one-time-code"></label><button class="btn" type="submit" style="min-height:44px">Entrar</button><button class="btn sec" type="button" data-a="lback">Trocar telefone</button></div></form>
 <form id="lfn" hidden novalidate class="stack" style="gap:10px"><label>CRN<br><input id="lcrn" style="width:100%;min-height:44px" placeholder="CRN-6 12345" autocomplete="username"></label><label>Senha<br><input id="lpw" type="password" style="width:100%;min-height:44px" autocomplete="current-password"></label><button class="btn" type="submit" style="min-height:44px">Entrar</button></form>
 <p id="lmsg" role="alert" style="text-align:center;margin:0;min-height:20px"></p><p class="note" style="text-align:center;margin:0">Seus dados de saúde são protegidos pela LGPD. Só você e sua equipe têm acesso.</p></div>`;
 $('#lfp').onsubmit=e=>{e.preventDefault();const m=$('#lmsg');m.style.color='var(--bad)';if($('#ls2').hidden){if($('#lph').value.replace(/\D/g,'').length<12){m.textContent='Telefone inválido';return}$('#ls1').hidden=true;$('#ls2').hidden=false;$('#lsent').textContent='Enviamos um código de 6 dígitos para '+$('#lph').value+'.';m.textContent='';$('#lcode').focus()}else{if(!/^\d{6}$/.test($('#lcode').value)){m.textContent='O código tem 6 dígitos';return}m.style.color='var(--accent)';m.textContent='Código aceito. Abrindo sua área…';setTimeout(()=>setView(S.onboarded?'pac':'onb'),700)}};
 $('#lfn').onsubmit=e=>{e.preventDefault();const m=$('#lmsg');m.style.color='var(--bad)';if($('#lcrn').value.trim().length<3){m.textContent='Informe o CRN';return}if($('#lpw').value.length<8){m.textContent='A senha tem ao menos 8 caracteres';return}m.textContent='CRN ou senha inválidos.'}}
const TERMS={care:['Termo de atendimento','Autorizo o tratamento dos meus dados pessoais e de saúde pelo nutricionista Lucas Bento, exclusivamente para a avaliação, o acompanhamento nutricional e a comunicação sobre o meu atendimento. Posso solicitar acesso, correção, exportação e exclusão dos meus dados a qualquer momento.'],clin:['Uso clínico de imagens','Autorizo o armazenamento de fotos corporais e de refeições para acompanhar minha evolução. As imagens ficam em ambiente privado e só são vistas por mim e pela equipe autorizada. Posso revogar quando quiser.'],pub:['Uso público de imagens','Autorizo, de forma opcional, a publicação de fotos de refeições na comunidade BentoNutriClub. Fotos clínicas nunca são publicadas. Posso revogar a qualquer momento e minhas publicações podem ser removidas.'],comm:['Comunicação','Autorizo receber lembretes e mensagens do meu nutricionista sobre o acompanhamento.']};
const CONS_META=[['care','Atendimento','Uso dos meus dados de saúde para o acompanhamento nutricional.',true],['clin','Fotos para uso clínico','Fotos corporais e de refeições, vistas só por mim e pela equipe.',false],['pub','Fotos no BentoNutriClub','Mostrar fotos de refeições na comunidade (opcional).',false],['comm','Lembretes e mensagens','Receber lembretes do meu nutricionista.',false]];
function drawOnb(){if(!S.onbInit){S.consent={care:false,clin:false,pub:false,comm:false};S.cdate={clin:null,pub:null,comm:null};S.onbInit=true}const st=S.onbStep||1,logo=LOGO_FULL;
 $('#onb').innerHTML=st===1?`<div class="phone" style="justify-content:center;text-align:center;gap:16px"><img alt="Lucas Bento Nutricionista" style="height:140px;align-self:center" src="${logo}"><h2>Bem-vinda ao BentoNutriSync</h2><p style="margin:0;color:var(--muted)">Seu acompanhamento nutricional em um só lugar: dieta, registros, evolução e conversa com o seu nutricionista.</p><button class="btn" data-a="onbnext" style="min-height:46px">Começar</button><p class="note" style="margin:0">Antes de começar, precisamos de algumas autorizações. Você escolhe o que compartilhar.</p></div>`:
 `<div class="phone"><div><h2 style="font-size:20px">Suas autorizações</h2><p class="note">Cada uma é separada. Você pode mudar quando quiser em Mais › Privacidade.</p></div>${CONS_META.map(([k,t,d,req])=>`<div class="consent"><div><b>${t}</b> ${req?'<span class="pill">obrigatório</span>':'<span class="pill mut">opcional</span>'}<div class="note" style="margin:2px 0 4px">${d}</div><button class="btn sec sm" data-a="term" data-k="${k}">Ler termo · v1.0</button></div><button class="tg" role="switch" aria-checked="${S.consent[k]}" aria-label="${t}" data-a="onbtg" data-k="${k}" ${req?'':''}></button></div>`).join('')}<button class="btn" data-a="onbdone" ${S.consent.care?'':'disabled'} style="min-height:46px">Continuar</button>${S.consent.care?'':'<p class="note" role="alert" style="margin:0;color:var(--bad)">O termo de atendimento é necessário para usar o aplicativo.</p>'}</div>`}
const NEXTMEAL=()=>{const d=DIETS[0].published;return d?d.meals.find(m=>m.time>='12:00')||d.meals[0]:null};
const PVIEWS={
 home(){const nm=NEXTMEAL(),w=S.water,goal=3000,fl=Math.floor(w/500);const ps=S.pstate;
  return`<div class="row2"><h2 style="font-size:20px">Bom dia, Marina</h2><span class="pill">87% adesão</span></div>
  <div class="card"><small>Meta de água</small><div class="water" style="margin:10px 0" role="img" aria-label="${fl} de 6 blocos de água">${Array.from({length:6},(_,i)=>`<i class="${i<fl?'f':''}"></i>`).join('')}</div><div class="row2"><span>${w.toLocaleString('pt-BR')} / 3.000 ml</span><button class="btn" data-a="water" ${w>=goal?'disabled':''}>${w>=goal?'Meta batida ✓':'+500 ml'}</button></div></div>
  <div class="card"><small>Treino</small>${ps.trained===null?`<div class="row2" style="margin-top:6px"><span>Treinou hoje?</span><span class="gap8"><button class="btn sec" data-a="train" data-v="1">Sim</button><button class="btn sec" data-a="train" data-v="0">Não</button></span></div>`:ps.trained==='ask'?`<div class="gap8" style="margin-top:8px"><select id="tm" aria-label="Modalidade">${['Musculação','Jiu-Jitsu','Corrida','Ciclismo','Natação','CrossFit','Futebol','Outro'].map(x=>`<option>${x}</option>`).join('')}</select><input id="td" type="number" placeholder="min" style="width:80px" aria-label="Duração em minutos"><button class="btn" data-a="trainsave">Salvar</button></div>${ps.err?'<p class="note" style="color:var(--bad)" role="alert">Informe a duração em minutos.</p>':''}`:`<div class="row2" style="margin-top:6px"><span>${ps.trained===false?'Sem treino hoje':'✓ '+ps.mod+' · '+ps.min+' min'}</span><button class="btn sec sm" data-a="train" data-v="r">Alterar</button></div>`}</div>
  <div class="card"><small>Próxima refeição</small>${nm?`<div style="font:700 18px var(--display);margin-top:4px">${nm.name} — ${nm.time}</div><div class="note">${nm.items.slice(0,3).map(i=>fmt(i.g,0)+' g '+F(i.fid).n.toLowerCase()).join(' · ')}</div>`:'<div class="note">Seu nutricionista ainda vai publicar sua dieta.</div>'}</div>
  <div class="gap8"><button class="btn" data-a="pv" data-v="diet" style="flex:1">Minha dieta</button><button class="btn" data-a="pv" data-v="meals" style="flex:1">Registrar refeição</button></div>`},
 diet(){const d=DIETS[0].published;if(!d)return`<h2 style="font-size:20px">Minha dieta</h2>${empty('Sua dieta ainda não foi publicada','Assim que o Lucas publicar, ela aparece aqui.')}`;
  const tot=sumN(d.meals.flatMap(m=>m.items.map(nut)));
  return`<div class="row2"><h2 style="font-size:20px">Minha dieta</h2><span class="pill">v${d.version} · publicada</span></div><div class="card"><div class="row2"><span><small class="lbl">Plano do dia</small><div style="font:800 24px var(--display)">${fmt(tot.k,0)} kcal</div></span><span class="note" style="margin:0;text-align:right">Publicada em ${d.date}<br>por Lucas Bento</span></div><div class="gap8" style="margin-top:8px"><span class="pill mut">P ${fmt(tot.p,0)} g</span><span class="pill mut">C ${fmt(tot.c,0)} g</span><span class="pill mut">G ${fmt(tot.f,0)} g</span></div></div>
  ${d.meals.map(m=>{const t=sumN(m.items.map(nut));return`<div class="card"><div class="row2"><b style="font-family:var(--display)">${m.name}</b><span class="note" style="margin:0">${m.time} · ${fmt(t.k,0)} kcal</span></div>${m.items.map(it=>{const f=F(it.fid);return`<div class="kv"><span>${f.n}<br><span class="note" style="margin:0">${hh(f,it.g)} · ${it.g} g</span></span><span>${fmt(nut(it).k,0)} kcal</span></div>`}).join('')}${m.items.some(i=>i.subs.length)?`<button class="btn sec sm" style="margin-top:8px" data-a="psub" data-id="${m.id}" aria-expanded="${!!S['ps'+m.id]}">${S['ps'+m.id]?'Ocultar':'Ver'} substituições</button>${S['ps'+m.id]?`<div class="sub" style="margin-top:6px">${m.items.filter(i=>i.subs.length).map(i=>{const n=nut(i);return i.subs.map(s=>{const sf=F(s);return`<div>${F(i.fid).n} ↔ ${Math.round(n.k/(sf.k/100)/5)*5} g de ${sf.n}</div>`}).join('')}).join('')}</div>`:''}`:''}</div>`}).join('')}<p class="note">Você vê sempre a versão publicada mais recente da sua dieta.</p>`},
 meals(){const ms=S.mealSel,ch=(arr,key,sel)=>arr.map(x=>`<button class="btn sec sm chip" data-a="msel" data-k="${key}" data-v="${x}" aria-pressed="${sel===x}">${x}</button>`).join('');
  return`<h2 style="font-size:20px">Registrar refeição</h2><div class="card"><small>Refeição</small><div class="gap8" style="margin:8px 0">${['Café da manhã','Almoço','Lanche da tarde','Jantar','Ceia'].map((x,i)=>`<button class="btn sec sm chip" data-a="msel" data-k="mt" data-v="${i}" aria-pressed="${ms.mt===i}">${x}</button>`).join('')}</div><div class="fig wide" style="margin:8px 0;aspect-ratio:4/3;max-height:none"><span class="cap">${S.mealPhoto?'Foto adicionada':'Foto da refeição (câmera ou galeria)'}</span></div><div class="gap8" style="margin-bottom:8px"><button class="btn sec sm" data-a="mphoto">📷 Câmera</button><button class="btn sec sm" data-a="mphoto">🖼 Galeria</button></div><small class="lbl">Como estava antes?</small><div class="gap8" style="margin:6px 0">${ch(['Ansioso','Muita fome','Tranquilo','Estressado','Sem fome','Outro'],'fb',ms.fb)}</div><small class="lbl">E depois?</small><div class="gap8" style="margin:6px 0">${ch(['Satisfeito','Estufado','Culpado','Energizado','Ainda com fome','Outro'],'fa',ms.fa)}</div><button class="btn" data-a="msave" style="width:100%" id="msv">Salvar refeição</button><p class="note" id="msm">Seus sentimentos são vistos apenas por você e pela sua equipe.</p></div>`},
 club(){return`<h2 style="font-size:20px">BentoNutriClub</h2><div class="card"><textarea id="cpt" rows="2" style="width:100%" placeholder="Compartilhe uma conquista, receita ou dica" aria-label="Nova publicação"></textarea><div class="row2" style="margin-top:6px"><button class="btn sec sm chip" data-a="cattach" aria-pressed="${S.attach}">📷 ${S.attach?'Foto anexada':'Anexar foto'}</button><button class="btn" data-a="cpub">Publicar</button></div><p class="note" id="cpm" role="status"></p></div><div id="pfeed" class="stack"></div>`},
 msg(){return`<h2 style="font-size:20px">Mensagens · Lucas Bento</h2><div class="card" id="pchat"></div>`},
 more(){const tg=([k,t,d,req])=>`<div class="kv" style="align-items:center"><span>${t}${req?' (obrigatório)':''}<br><span class="note" style="margin:0">${S.consent[k]?(S.cdate[k]?'Aceito em '+S.cdate[k]+' · v1.0':d):'Não autorizado'}</span></span><button class="tg" role="switch" aria-checked="${S.consent[k]}" aria-label="${t}" data-a="ptg" data-k="${k}" ${req?'disabled':''}></button></div>`;
  return`<h2 style="font-size:20px">Mais</h2><div class="card"><div class="row2"><b>Minha evolução</b><span class="pill">3 consultas</span></div>${lc(PAT[0].w,DATES,'kg')}${kv([['Peso','−1,5 kg'],['Cintura','−2,5 cm'],['% gordura','−1,8 p.p.']])}</div>
  <div class="card"><b>Meu perfil</b>${kv([['Nome','Marina Costa'],['Telefone','+55 (83) 99123-8792'],['Nutricionista','Lucas Bento']])}</div>
  <div class="card"><b>Privacidade</b><p class="note" style="margin:4px 0 8px">Você decide o que compartilhar e pode mudar quando quiser.</p>${CONS_META.map(tg).join('')}<div class="gap8" style="margin-top:10px"><button class="btn sec sm" data-a="pexport">Exportar meus dados</button><button class="btn sec sm" data-a="pdelete">Solicitar exclusão</button></div></div><button class="btn sec" data-a="pout">Sair</button>`}
};
const PTABS=[['home','Home'],['diet','Dieta'],['meals','Refeições'],['club','Clube'],['msg','Chat'],['more','Mais']];
function drawPac(){S.pvLoaded=true;$('#pac').innerHTML=`<div class="phone"><div class="pv" id="pbody" aria-live="polite"></div><nav class="pnav" aria-label="Menu do paciente">${PTABS.map(([k,t])=>`<button data-a="pv" data-v="${k}" aria-current="${S.pv===k}">${t}${k==='msg'&&S.unread?'<span class="pill" style="margin-left:2px;padding:0 6px">1</span>':''}</button>`).join('')}</nav></div>`;drawPv()}
function drawPv(){$('#pbody').innerHTML=PVIEWS[S.pv]();$$('.pnav button').forEach(b=>{b.setAttribute('aria-current',b.dataset.v===S.pv);if(b.dataset.v==='msg'&&S.pv==='msg'){const s=$('.pill',b);s&&s.remove()}});
 if(S.pv==='club')feeds();if(S.pv==='msg'){S.unread=false;CHAT[0].forEach(m=>{if(m.me===1)m.read=true});chatBox(0,'#pchat',true)}}
