/* ================= extração da anamnese (regras locais; nada sai do sistema) ================= */
const RULES=[['Dorme',/dorm\w*\s+(?:às|as)?\s*(\d{1,2})\s*h?:?(\d{2})?/i,m=>m[1].padStart(2,'0')+':'+(m[2]||'00')],['Acorda',/(?<!\w)acord\w*\s+(?:às|as)\s*(\d{1,2})\s*h?:?(\d{2})?/i,m=>m[1].padStart(2,'0')+':'+(m[2]||'00')],['Despertares',/acorda\w*\s+(\d+)\s+vez/i,m=>m[1]],['Alergia',/al[ée]rgic[oa]\s+a\s+([^.,;]+)/i,m=>m[1]],['Água',/(\d+(?:[.,]\d+)?)\s*litros?\s+de\s+[áa]gua/i,m=>m[1]+' L/dia'],['Refluxo/Azia',/\b((?:refluxo|azia)[^.,;]*)/i,m=>m[1]],['Escala de Bristol',/bristol\s*([1-7])/i,m=>'Tipo '+m[1]],['Suplemento',/(?:usa|toma)\s+((?:creatina|whey|vitamina)[^.;]*)/i,m=>m[1]]];
S.ai=[];S.aiEdit=null;
const aiRender=()=>{const o=$('#ao');if(!o)return;const pend=S.ai.filter(i=>i.s==='pending').length,ok=S.ai.filter(i=>i.s==='confirmed'||i.s==='edited').length,L={pending:'pendente',confirmed:'confirmado',edited:'editado',rejected:'excluído'};
 o.innerHTML=`<small>Dados extraídos da anamnese · ${pend} aguardando</small>`+(S.ai.length?S.ai.map((i,k)=>`<div class="review"><div style="min-width:0;flex:1"><b>${i.f}:</b> ${S.aiEdit===k?`<input id="aei" value="${i.v}" style="width:60%" aria-label="Editar valor"> <button class="btn sm" data-a="aisave" data-k="${k}">Salvar</button>`:i.v} <span class="pill ${i.s==='pending'?'warn':i.s==='rejected'?'bad':''}">${L[i.s]}</span><div class="note" style="margin:0">origem: “${i.src}” · confiança: n/d (extração por regras)</div></div><span class="gap8"><button class="btn sec sm" data-a="aiedit" data-k="${k}">Editar</button><button class="btn sec sm" data-a="aireject" data-k="${k}">Excluir</button><button class="btn sm" data-a="aiok" data-k="${k}">Confirmar</button></span></div>`).join('')+`<div class="row2" style="margin-top:10px"><span class="note" style="margin:0"><b>${ok}</b> item(ns) serão salvos no prontuário. Nada é salvo sem confirmação.</span><button class="btn" data-a="aisavepr" ${pend?'disabled':''}>Salvar no prontuário</button></div>`:empty('Nada encontrado','O texto não trouxe informações reconhecíveis. Você pode adicionar manualmente.'))};
/* ================= formulário de novo paciente ================= */
S.np={mods:[],sec:[],sport:false};
function drawNewPat(){const chips=(a,k,sel)=>a.map(x=>`<button type="button" class="btn sec sm chip" data-a="npchip" data-k="${k}" data-v="${x}" aria-pressed="${sel.includes(x)}">${x}</button>`).join('');
 const G=['Emagrecimento','Hipertrofia','Performance','Recomposição corporal','Manutenção','Saúde','Outro'];
 render(`<button class="btn sec" data-a="nav" data-k="patients">← Pacientes</button><h2 style="margin:12px 0">Novo paciente</h2><form id="npf" class="stack" novalidate>
 <div class="card stack"><small>Dados pessoais</small><label>Nome completo *<br><input id="n_name" style="width:100%" autocomplete="off"><span class="note err" id="e_name" role="alert" style="color:var(--bad)"></span></label><div class="grid2"><label>Nascimento *<br><input id="n_birth" type="date" style="width:100%"><span class="note err" id="e_birth" role="alert" style="color:var(--bad)"></span></label><label>Sexo biológico *<br><select id="n_sex" style="width:100%"><option value="">Selecione</option><option>Feminino</option><option>Masculino</option></select><span class="note">Usado nos cálculos de gasto energético.</span><span class="note err" id="e_sex" role="alert" style="color:var(--bad)"></span></label></div>
 <label>Telefone * (será o login do paciente)<br><input id="n_phone" data-i="phone" inputmode="tel" placeholder="+55 (83) 99999-9999" style="width:100%"><span class="note err" id="e_phone" role="alert" style="color:var(--bad)"></span></label>
 <div class="grid2"><label>E-mail (opcional)<br><input id="n_mail" type="email" style="width:100%"></label><label>CEP (opcional)<br><input id="n_cep" data-i="cep" inputmode="numeric" maxlength="9" placeholder="00000-000" style="width:100%"><span class="note" id="n_addr">O endereço não é obrigatório.</span></label></div></div>
 <div class="card stack"><small>Objetivo</small><label>Objetivo principal *<br><select id="n_goal" style="width:100%"><option value="">Selecione</option>${G.map(g=>`<option>${g}</option>`).join('')}</select><span class="note err" id="e_goal" role="alert" style="color:var(--bad)"></span></label><div><span class="lbl">Objetivos secundários</span><div class="gap8" style="margin-top:6px">${chips(G,'sec',S.np.sec)}</div></div></div>
 <div class="card stack"><small>Perfil esportivo</small><label class="gap8"><input type="checkbox" id="n_sport" data-i="npsport" style="min-height:0" ${S.np.sport?'checked':''}> Pratica esportes</label>${S.np.sport?`<div class="gap8">${chips(['Musculação','Jiu-Jitsu','Corrida','Ciclismo','Natação','CrossFit','Futebol','Outro'],'mods',S.np.mods)}</div><div class="grid2"><label>Frequência semanal<br><input type="number" min="0" max="14" value="3" style="width:100%"></label><label>Modalidade principal<br><select style="width:100%">${S.np.mods.map(m=>`<option>${m}</option>`).join('')||'<option value="">Marque as modalidades</option>'}</select></label></div>`:''}</div>
 <div class="card stack"><small>Informações opcionais</small><div class="grid2"><label>Etnia<br><input style="width:100%"></label><label>Identidade de gênero<br><input style="width:100%"></label></div><p class="note" style="margin:0">Opcionais. Usadas só para personalização autorizada e nunca entram em fórmulas.</p></div>
 <div class="banner" id="npbanner" hidden></div>
 <div class="row2"><label class="gap8 note" style="margin:0"><input type="checkbox" id="simfail" style="min-height:0"> Simular falha de conexão (demonstração)</label><span class="gap8"><button type="button" class="btn sec" data-a="nav" data-k="patients">Cancelar</button><button type="submit" class="btn" id="npsave">Salvar paciente</button></span></div></form>`,()=>{$('#npf').onsubmit=A.patsave},false)}
A_extra.patsave=ev=>{ev.preventDefault();const v=id=>$('#'+id).value.trim(),err=(k,m)=>{$('#e_'+k).textContent=m;return !m},b=$('#npbanner');b.hidden=true;
 const okn=err('name',v('n_name').length<3?'Informe o nome completo':''),bd=v('n_birth'),okb=err('birth',!bd?'Informe a data de nascimento':bd>'2026-10-01'?'Data futura':''),oks=err('sex',v('n_sex')?'':'Obrigatório para os cálculos'),okp=err('phone',v('n_phone').replace(/\D/g,'').length<12?'Telefone inválido':''),okg=err('goal',v('n_goal')?'':'Escolha o objetivo principal');
 if(!(okn&&okb&&oks&&okp&&okg)){b.hidden=false;b.className='banner bad';b.setAttribute('role','alert');b.innerHTML='<span>Revise os campos destacados.</span>';const f=$('.err:not(:empty)');f&&f.previousElementSibling&&f.previousElementSibling.focus&&f.previousElementSibling.focus();return}
 const btn=$('#npsave');btn.disabled=true;btn.innerHTML='<span class="spin"></span> Salvando…';
 setTimeout(()=>{if($('#simfail').checked){btn.disabled=false;btn.textContent='Tentar novamente';b.hidden=false;b.className='banner bad';b.setAttribute('role','alert');b.innerHTML='<span>Não foi possível salvar. Tente novamente.</span>';return}
  const id=PAT.length,np={...PAT[3],id,name:v('n_name'),sex:v('n_sex')==='Feminino'?'F':'M',goal:v('n_goal'),st:'ok',last:'—',adh:0,ret:'—',lc:'—',diet:'none',dv:0,vet:null,pic:v('n_name').split(' ')[0],phone:v('n_phone'),age:Math.max(1,2026-new Date(bd).getFullYear())};
  PAT.push(np);DIETS[id]={status:'none',version:0,meals:[]};CONS[id]=[['01/10','Inicial','Agendada','sched']];CHAT[id]=[];toast('Paciente cadastrado. Enviamos o convite por SMS.');S.np={mods:[],sec:[],sport:false};go('patients')},700)};
Object.assign(I,{phone(el){el.value=phMask(el.value)},cep(el){const d=el.value.replace(/\D/g,'').slice(0,8);el.value=d.length>5?d.slice(0,5)+'-'+d.slice(5):d;$('#n_addr').textContent=d.length===8?'João Pessoa · PB · Rua Exemplo, bairro Centro (preenchido pelo CEP)':'O endereço não é obrigatório.'},npsport(el){S.np.sport=el.checked;drawNewPat()}});
/* ================= ações ================= */
const A={
 theme(){const r=document.documentElement,dark=r.dataset.theme==='dark'||(!r.dataset.theme&&matchMedia('(prefers-color-scheme:dark)').matches);r.dataset.theme=dark?'light':'dark'},
 view(el){setView(el.dataset.v)},nav(el){go(el.dataset.k)},open(el){open_(el.dataset.id,el.dataset.t)},tab(el){setTab(el.dataset.t)},toast(el){toast(el.dataset.m)},
 newpat(){S.nav='patients';drawNav();drawNewPat()},clearf(){const st=VIEWS.patients.st;st.q='';st.f='all';$('#psq').value='';$$('[data-f]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.f==='all'));VIEWS.patients.rows()},
 pfilter(el){VIEWS.patients.st.f=el.dataset.f;$$('#pfl [data-f]').forEach(b=>b.setAttribute('aria-pressed',b===el));VIEWS.patients.rows()},
 conv(el){$$('.conv').forEach(x=>x.removeAttribute('aria-current'));el.setAttribute('aria-current','true');chatBox(+el.dataset.id,'#chatbox');if(el.dataset.id==='0'){S.unread=false;const p=$('.pill',el);p&&p.remove()}},
 tg(el){if(!el.disabled)el.setAttribute('aria-checked',el.getAttribute('aria-checked')!=='true')},
 mclose:closeModal,'mclose-bg'(el,e){if(e.target===el)closeModal()},
 /* histórico */
 amend(el){const i=el.dataset.i;modal(`<h3>Emendar consulta de ${CONS[S.pid][i][0]}</h3><p>O valor original será preservado. Informe o motivo da alteração.</p><label>Motivo *<br><input id="amr" style="width:100%" placeholder="ex.: erro de digitação na cintura"></label><p class="note err" id="ame" role="alert" style="color:var(--bad)"></p><div class="gap8" style="justify-content:flex-end;margin-top:10px"><button class="btn sec" data-a="mclose">Cancelar</button><button class="btn" data-a="amendok" data-i="${i}">Registrar emenda</button></div>`)},
 amendok(el){if($('#amr').value.trim().length<5){$('#ame').textContent='Informe o motivo (mín. 5 caracteres).';return}CONS[S.pid][el.dataset.i][3]='amended';closeModal();toast('Emenda registrada. Original preservado.');setTab('Histórico',false)},
 orig(el){modal(`<h3>Valores originais · consulta de ${CONS[S.pid][el.dataset.i][0]}</h3><div class="tbl"><table style="min-width:300px"><thead><tr><th>Campo</th><th>Original</th><th>Após a emenda</th></tr></thead><tbody><tr><td>Coxa medial D</td><td>56,8 cm</td><td>57,2 cm</td></tr></tbody></table></div><p class="note">Emendado por Lucas Bento em 14/08/2026 · motivo: "perímetro de coxa corrigido".</p><div style="text-align:right;margin-top:10px"><button class="btn" data-a="mclose">Fechar</button></div>`)},
 finalize(el){modal(`<h3>Finalizar a consulta?</h3><p>Depois de finalizada, os dados ficam preservados. Alterações futuras passam por emenda com motivo.</p><div class="gap8" style="justify-content:flex-end;margin-top:14px"><button class="btn sec" data-a="mclose">Cancelar</button><button class="btn" data-a="finok" data-i="${el.dataset.i}">Finalizar</button></div>`)},
 finok(el){CONS[S.pid][el.dataset.i][3]='finalized';CONS[S.pid][el.dataset.i][2]='Finalizada';closeModal();toast('Consulta finalizada.');setTab('Histórico',false)},
 /* anamnese */
 extract(){const t=($('#at').value||'').trim();if(!t){S.ai=[];aiRender();toast('Escreva ou grave o relato do paciente.');return}S.ai=[];t.split(/(?<=[.!?])\s+/).forEach(sn=>RULES.forEach(r=>{const m=sn.match(r[1]);if(m)S.ai.push({f:r[0],v:r[2](m),src:sn.trim(),s:'pending'})}));S.aiEdit=null;aiRender()},
 aiok(el){S.ai[el.dataset.k].s='confirmed';aiRender()},aireject(el){S.ai[el.dataset.k].s='rejected';aiRender()},aiedit(el){S.aiEdit=+el.dataset.k;aiRender();$('#aei').focus()},
 aisave(el){const v=$('#aei').value.trim();if(v){S.ai[el.dataset.k].v=v;S.ai[el.dataset.k].s='edited'}S.aiEdit=null;aiRender()},aisavepr(){toast(S.ai.filter(i=>i.s==='confirmed'||i.s==='edited').length+' itens salvos no prontuário.')},
 skcalc(){$('#skm').innerHTML='<b>Equação em validação científica.</b> Este protocolo será liberado após a conferência na referência original. Enquanto isso, use a densidade medida ao lado.'},
 /* feedback */
 badge(el){$$('[data-b]').forEach(b=>b.setAttribute('aria-pressed','false'));el.setAttribute('aria-pressed','true')},
 fbsend(){const b=$('[data-b][aria-pressed=true]'),x=$('#fbt').value.trim(),a=!$('#fba').hidden;$('#fbm').textContent=(b||x||a)?'Enviado: '+[b&&b.dataset.b,x,a&&'áudio'].filter(Boolean).join(' · '):'Escolha um selo, escreva ou grave um áudio.'},
 mreply(el){const r=MEALLOG[el.dataset.i];modal(`<h3>Responder · ${r[0]}</h3><div class="gap8" style="margin:10px 0">${BADGES.map(b=>`<button class="btn sec sm chip" data-a="badge" data-b="${b}" aria-pressed="false">${b}</button>`).join('')}</div><textarea id="fbt" rows="2" style="width:100%" placeholder="Mensagem curta (opcional)"></textarea><div class="gap8" style="justify-content:flex-end;margin-top:10px"><button class="btn sec" data-a="mclose">Cancelar</button><button class="btn" data-a="mreplyok">Enviar</button></div>`)},
 mreplyok(){closeModal();toast('Resposta enviada ao paciente.')},
 /* áudio e chat */
 recstart(el){const box=el.closest('.recbox'),id=box.dataset.id;box.dataset.idle=box.innerHTML;REC[id]={t:0};box.innerHTML=`<span class="rec" role="status"><span class="wave" aria-hidden="true">${'<i></i>'.repeat(7)}</span><span class="rt">0:00</span><button class="btn sm" data-a="recstop" style="background:var(--bad);color:#fff" aria-label="Parar gravação">■ Parar</button></span>`;REC[id].iv=setInterval(()=>{REC[id].t++;const r=$('.rt',box);r&&(r.textContent='0:'+String(REC[id].t).padStart(2,'0'))},1000)},
 recstop(el){const box=el.closest('.recbox'),id=box.dataset.id,r=REC[id];clearInterval(r.iv);const sec=Math.max(r.t,3);box.innerHTML=`<span class="gap8" role="status"><span class="spin"></span> ${id==='anam'?'Transcrevendo…':'Enviando…'}</span>`;setTimeout(()=>{box.innerHTML=box.dataset.idle;DONE[box.dataset.done](sec,box)},800)},
 play(el){const b=el.closest('.aud').querySelector('.tr i'),s=+el.dataset.s;if(el.dataset.on){clearTimeout(el._t);b.style.transition='none';b.style.width='0';el.textContent='▶';delete el.dataset.on;return}el.dataset.on=1;el.textContent='⏸';b.style.transition='none';b.style.width='0';requestAnimationFrame(()=>{b.style.transition='width '+s+'s linear';b.style.width='100%'});el._t=setTimeout(()=>{el.textContent='▶';delete el.dataset.on;b.style.transition='none';b.style.width='0'},s*1000+100)},
 send(el){const i=$('#ci'),t=i.value.trim();if(!t){i.focus();return}const pid=+el.dataset.pid,pat=el.dataset.pat==='1';CHAT[pid].push({me:pat?0:1,t,h:'agora'});chatBox(pid,pat?'#pchat':'#chatbox',pat)},
 upl(){const o=$('#upp');o.innerHTML='<div><div class="row2"><span>frente.jpg · comprimindo…</span><span id="upn">0%</span></div><div class="bar"><i id="upb" style="width:0"></i></div></div>';let n=0;const iv=setInterval(()=>{n+=12+Math.floor(Math.random()*10);if(n>=100){n=100;clearInterval(iv);setTimeout(()=>{o.innerHTML='<div class="banner ok"><span>✓ frente.webp enviada (312 KB, reduzida de 3,8 MB)</span></div>'},300)}$('#upn')&&($('#upn').textContent=n+'%');$('#upb')&&($('#upb').style.width=n+'%')},220)},
 /* comunidade */
 pfeat(el){const p=S.posts.find(x=>x.id==el.dataset.id);p.f=p.f?0:1;feeds()},phide(el){const p=S.posts.find(x=>x.id==el.dataset.id);p.st=p.st==='h'?'v':'h';feeds()},pdel(el){S.posts.find(x=>x.id==el.dataset.id).st='d';feeds()},
 plike(el){S.liked[el.dataset.id]=!S.liked[el.dataset.id];feeds()},pcm(el){S.openCm[el.dataset.id]=!S.openCm[el.dataset.id];feeds()},
 cmadd(el){const i=$('#cmi'+el.dataset.id),t=i.value.trim();if(!t){i.focus();return}S.posts.find(x=>x.id==el.dataset.id).cm.push({a:'Mari',t});feeds();const n=$('#cmi'+el.dataset.id);n&&n.focus()},cmdel(el){S.posts.find(x=>x.id==el.dataset.id).cm.splice(+el.dataset.i,1);feeds()},
 chjoin(el){const c=S.challenges.find(x=>x.id==el.dataset.id);c.joined=!c.joined;feeds();toast(c.joined?'Você entrou no desafio.':'Você saiu do desafio.')},
 official(){S.posts.unshift({id:Date.now(),a:'BentoNutri',k:'Oficial',t:'Dica da semana: hidrate-se ao longo do dia, não só nas refeições.',l:0,c:0,st:'v',f:1,img:0,cm:[]});feeds();toast('Conteúdo oficial publicado.')},
 newchal(){modal(`<h3>Criar desafio</h3><div class="stack"><label>Título *<br><input id="chn" style="width:100%" placeholder="ex.: 3 refeições com foto por dia"></label><label>Descrição<br><textarea id="chd" rows="2" style="width:100%"></textarea></label><div class="grid2"><label>Início<br><input id="chs" type="date" value="2026-10-05" style="width:100%"></label><label>Fim<br><input id="che" type="date" value="2026-10-12" style="width:100%"></label></div><p class="note err" id="che2" role="alert" style="color:var(--bad)"></p></div><div class="gap8" style="justify-content:flex-end;margin-top:10px"><button class="btn sec" data-a="mclose">Cancelar</button><button class="btn" data-a="chsave">Publicar desafio</button></div>`)},
 chsave(){const t=$('#chn').value.trim(),s=$('#chs').value,e=$('#che').value;if(!t){$('#che2').textContent='Informe o título.';return}if(e<s){$('#che2').textContent='O fim deve ser depois do início.';return}const f=d=>d.slice(8)+'/'+d.slice(5,7);S.challenges.unshift({id:Date.now(),title:t,desc:$('#chd').value.trim()||'Participe e acompanhe seu progresso.',start:f(s),end:f(e),joined:false,done:0});closeModal();feeds();toast('Desafio publicado para a comunidade.')},
 /* paciente */
 pv(el){S.pv=el.dataset.v;drawPv()},water(){S.water=Math.min(3000,S.water+500);drawPv()},
 train(el){const v=el.dataset.v;S.pstate=v==='0'?{trained:false}:{trained:'ask',err:false,mod:'Musculação',min:''};drawPv()},
 trainsave(){const m=+$('#td').value;if(!(m>0)){S.pstate.err=true;drawPv();return}S.pstate={trained:true,mod:$('#tm').value,min:m};drawPv();toast('Treino registrado.')},
 psub(el){S['ps'+el.dataset.id]=!S['ps'+el.dataset.id];drawPv()},
 msel(el){S.mealSel[el.dataset.k]=el.dataset.k==='mt'?+el.dataset.v:(S.mealSel[el.dataset.k]===el.dataset.v?null:el.dataset.v);drawPv()},mphoto(){S.mealPhoto=true;drawPv()},
 msave(el){el.disabled=true;el.innerHTML='<span class="spin"></span> Salvando…';setTimeout(()=>{const ms=S.mealSel;S.mealPhoto=false;S.mealSel={mt:1,fb:null,fa:null};drawPv();$('#msm').textContent=(ms.fb&&ms.fa)?'Refeição salva. Boa!':'Salvo sem os sentimentos. Você pode completar depois.';toast('Refeição registrada.')},650)},
 cattach(){S.attach=!S.attach;const t=$('#cpt').value;drawPv();$('#cpt').value=t;if(S.attach&&!S.consent.pub){$('#cpm').innerHTML='Para publicar fotos, autorize o uso público de imagem. Fotos clínicas nunca são publicadas. <button class="btn sm" data-a="authpub">Autorizar uso público</button>'}},
 authpub(){S.consent.pub=true;S.cdate.pub='01/10/2026';toast('Uso público autorizado (v1.0).');const t=$('#cpt').value;drawPv();$('#cpt').value=t},
 cpub(){const t=$('#cpt').value.trim();if(!t){$('#cpm').textContent='Escreva algo para publicar.';return}if(S.attach&&!S.consent.pub){$('#cpm').textContent='Foto não anexada: falta o consentimento de uso público.';return}S.posts.unshift({id:Date.now(),a:'Mari',k:'Conquista',t,l:0,c:0,st:'v',f:0,img:S.attach?1:0,cm:[]});S.attach=false;drawPv();$('#cpm').textContent='Publicado.'},
 ptg(el){const k=el.dataset.k;if(S.consent[k]){modal(`<h3>Revogar autorização?</h3><p>${k==='clin'?'Novas fotos não poderão ser salvas no seu prontuário. As já enviadas continuam protegidas.':k==='pub'?'Suas fotos deixarão de aparecer na comunidade.':'Você deixará de receber lembretes.'}</p><div class="gap8" style="justify-content:flex-end;margin-top:14px"><button class="btn sec" data-a="mclose">Manter</button><button class="btn" data-a="revoke" data-k="${k}">Revogar</button></div>`)}else{S.consent[k]=true;S.cdate[k]='01/10/2026';toast('Autorização registrada (v1.0).');drawPv()}},
 revoke(el){S.consent[el.dataset.k]=false;closeModal();toast('Autorização revogada em 01/10/2026.');drawPv()},
 pexport(){toast('Exportação pedida. Você receberá um arquivo com todos os seus dados.')},
 pdelete(){modal(`<h3>Solicitar exclusão dos dados?</h3><p>Seu nutricionista será avisado. Alguns dados podem precisar ser mantidos por obrigação legal; você será informada sobre isso.</p><div class="gap8" style="justify-content:flex-end;margin-top:14px"><button class="btn sec" data-a="mclose">Cancelar</button><button class="btn" data-a="pdelok">Solicitar exclusão</button></div>`)},pdelok(){closeModal();toast('Pedido de exclusão registrado.')},
 pout(){setView('login')},
 lmode(el){const p=el.dataset.m==='p';$('#lmp').setAttribute('aria-pressed',p);$('#lmn').setAttribute('aria-pressed',!p);$('#lfp').hidden=!p;$('#lfn').hidden=p;$('#lmsg').textContent=''},
 lback(){$('#ls2').hidden=true;$('#ls1').hidden=false;$('#lmsg').textContent=''},
 onbnext(){S.onbStep=2;drawOnb()},onbtg(el){const k=el.dataset.k;S.consent[k]=!S.consent[k];S.cdate[k]=S.consent[k]?'01/10/2026':null;drawOnb()},
 onbdone(){S.onboarded=true;S.onbStep=1;setView('pac');toast('Tudo pronto. Bem-vinda!')},
 term(el){const t=TERMS[el.dataset.k];modal(`<h3>${t[0]} · v1.0</h3><p>${t[1]}</p><div style="text-align:right;margin-top:10px"><button class="btn" data-a="mclose">Fechar</button></div>`)},
 npchip(el){const k=el.dataset.k,a=S.np[k],v=el.dataset.v;S.np[k]=a.includes(v)?a.filter(x=>x!==v):[...a,v];const keep={n:$('#n_name').value,b:$('#n_birth').value,s:$('#n_sex').value,p:$('#n_phone').value,g:$('#n_goal').value};drawNewPat();$('#n_name').value=keep.n;$('#n_birth').value=keep.b;$('#n_sex').value=keep.s;$('#n_phone').value=keep.p;$('#n_goal').value=keep.g}
};
Object.assign(A,A_extra);
/* ================= eventos e inicialização ================= */
document.addEventListener('click',e=>{const el=e.target.closest('[data-a]');if(el&&A[el.dataset.a]){if(el.tagName==='A')e.preventDefault();A[el.dataset.a](el,e)}});
document.addEventListener('input',e=>{const t=e.target,n=t.dataset&&t.dataset.i;if(n&&I[n]&&t.tagName!=='SELECT'&&t.type!=='checkbox')I[n](t)});
document.addEventListener('change',e=>{const t=e.target,n=t.dataset&&t.dataset.i;if(n&&I[n]&&(t.tagName==='SELECT'||t.type==='checkbox'))I[n](t);const c=t.dataset&&t.dataset.c;if(c&&C[c])C[c](t)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#layer').innerHTML)closeModal();if((e.key==='Enter'||e.key===' ')&&e.target.matches('tr[data-a],.card[data-a],.conv[data-a]')){e.preventDefault();e.target.click()}});
function setView(v){S.view=v;['login','onb','nutri','pac'].forEach(x=>$('#'+x).classList.toggle('on',x===v));$$('.seg [data-v]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.v===v));if(v==='login')drawLogin();if(v==='onb'){S.onbStep=S.onbStep||1;drawOnb()}if(v==='pac'){S.pv=S.pv||'home';drawPac()}if(v==='nutri'){drawNav();if(!S.pid&&S.nav!=='patients')VIEWS[S.nav]()}}
drawNav();VIEWS.dash();
